### ISSUE TITLE
Problema con integrazione

### ISSUE THREAD

**Issue by felisida** [sdesalve/zcsazzurro#3]
Ciao ho seguito le istruzioni, ma evidentemente sbaglio qualcosa. ricapitolando: 

- ho copiato la cartella zcsazzurro dento Custom_components
- ho chiesto il codice di autorizzazione a zucchetti il quale mi ha inviato il pdf (nel codice c'è uno spazio)
- ho riporta S/N ed auth nel codice ho provato a metterli sotto virgolette "", apici '', ed anche senza nulla
- ho copiato in configuration il codice per la creazione dei vari sensori,
 conclusione i sensori mi vengono creati ma non leggono nulla.
ti allego qualche screenshot magari riesci ad aiutarmi a capire dove sbaglio

![Schermata 2021-11-29 alle 11 16 07](https://user-images.githubusercontent.com/51525150/143850916-24a867e0-3b6d-43ce-ab14-cfd62695061b.jpg)
![Schermata 2021-11-29 alle 11 12 44](https://user-images.githubusercontent.com/51525150/143850919-ab981fad-d8fd-4d96-a94c-2f97630dd646.jpg)
![Schermata 2021-11-29 alle 11 12 28](https://user-images.githubusercontent.com/51525150/143850928-b442110e-b344-47ac-b863-5d645c7a4e79.jpg)
![Schermata 2021-11-29 alle 11 12 10](https://user-images.githubusercontent.com/51525150/143850931-974fed34-8b0b-4255-b183-1ab4c17ac98c.jpg)

**Comment by sdesalve** [comment]
Please Send me an email with your thingkey and authkey

**Comment by felisida** [comment]
Ok, thanks a lot,
My info
S/N: 0806309223
authkey:  Zcs eHWAeEq0aYO0

Attahched you will find the mail with authkey

Saluti Felice
Il 29 nov 2021, 14:27 +0100, sdesalve ***@***.***>, ha scritto:

**Comment by sdesalve** [comment]
I've redacted you personal info.

your S/N should be like this:

```
- platform: zcsazzurro
  name: test_zcsazzurro
  thingkey: "zm1es999xxx999"
  authkey: "Zcs eHWAeEq0aYO0"
```

please send PDF to my mail

me

chiocciola

sdesalve

.it

**Comment by murraythegoz** [comment]
Same problem here.

I get something like:
2021-12-06 11:42:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{% set energy = states.sensor.fotovoltaico.attributes.current.energyGenerating | float | default (0) %} {{ energy | round(2) }}'

It seems there is a mismatch in name definition into the instructions
When defining the pointer, the sensor is defined as "test_zcsazzurro" but found no reference to it in both integration sensor and in templates.

Trying to dig into the code but due to my lack of HA component I was not able to find a consistent naming.

Will send my thingykey and autkey if you wish to.

thank you

m.

**Comment by sdesalve** [comment]
test_zcsazzurro is the name that you give to your sensor. In your log I see "fotovoltaico".

Have you defined your sensor correctly and gaved the same name?

In pratica se lo dichiari come test_zcsazzurro non puoi interrogarlo come fotovoltaico. Obviously

**Comment by murraythegoz** [comment]
> test_zcsazzurro is the name that you give to your sensor. In your log I see "fotovoltaico".
> 
> Have you defined your sensor correctly and gaved the same name?
sensor:
  - platform: zcsazzurro
    name: fotovoltaico
    thingkey: "ZM1XXXXXXXX"
    authkey: "Zcs eHWAeEq0aYO0"

but I made a mistake since I use the splitted config, thus the "sensor:"  keyword should not be used.
Now I have a sensor defined.

but I get a fetch error.
2021-12-06 12:23:10 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: https://third.zcsazzurroportal.com:19003 failed with 
2021-12-06 12:23:10 ERROR (MainThread) [custom_components.zcsazzurro.sensor] Unable to start fetching data from ZCSAzzurro
2021-12-06 12:23:10 WARNING (MainThread) [custom_components.zcsazzurro.sensor] Empty reply found when expecting JSON data
2021-12-06 12:23:10 DEBUG (MainThread) [custom_components.zcsazzurro.sensor] Return the state: False

**Comment by murraythegoz** [comment]
thingykey is :thingkey: "ZM1ES060M79390"

**Comment by sdesalve** [comment]
I heared that on this weeks API server should be under maintenance. The log is reporting that Hassio was unable to get data from remote server...

Please try to leave hassio get data correctly

**Comment by murraythegoz** [comment]
ok thank you.

will keep the conf as is, and in case will get beck to you by next week

thank you

m.

**Comment by stavrosso** [comment]
Hello @sdesalve 

Is the intergration working?

I requested the Api from ZCS and they sent the pdf file

I created a sensor in my sensor.yaml (which is referenced in configuration.yaml) 

`- platform: zcsazzurro
  name: fotovoltaico
  thingkey: "zb1esxxxkarxxx"
  authkey: "Zcs xXXXxXx0xXX0"`

and a template sensor in configuration.yaml like

`template:
- sensor:
    - name: "Instant Power"
      unit_of_measurement: "W"
      state: >
        {% set power = states.sensor.fotovoltaico.attributes.current.powerGenerating | int | default (0) %}
        {{ power }}
      state_class: measurement
      device_class: power
      icon: mdi:solar-power`

I can not get any feedback from the sensor , Am I doing something wrong or is there a problem with the integration?

Thank you

**Comment by sdesalve** [comment]
> Am I doing something wrong

Can you post your Hassio LOGS? Otherwise I can't realize what's wrong with your config

Anyway ZCS is migrating their APIs to a new server and will be replaced soon. So it's working bad lately

**Comment by murraythegoz** [comment]
As a side note, the error "Template variable error: 'None' has no attribute 'attributes' when rendering '{% set energy = states.sensor.fotovoltaico.attributes.current.energyGenerating | float | default (0) %} {{ energy | round(2) }}'" happens when the automation cannot fetch from server.

Once a value is fetched at least once, the shcema is populated and such errors seems to disappear.
(the "empty response" from the servers keeps bothering me but this is problem on their side )

Please add a note on troubleshooting so you will get less complains about this :-).
